### ISSUE TITLE
Notice in case comment module is not enabled

### ISSUE THREAD

**Issue by regilero** [makinacorpus/drupal-quotedown#2]
<pre>
Notice : Use of undefined constant COMMENT_NODE_OPEN - assumed 'COMMENT_NODE_OPEN' in quotedown_node_view_alter() (line 67 in www/sites/all/modules/drupal-quotedown/quotedown.module).
</pre>

Proposed fix : 
https://github.com/makinacorpus/drupal-quotedown/blob/master/quotedown.module#L66

    if (COMMENT_NODE_OPEN != $build['#node']->comment || in_array($build['#node']->type, variable_get(QUOTEDOWN_VAR_DISABLED_NODE_TYPE, array()))) {
      return;
    }

to:

    if ( in_array($build['#node']->type, variable_get(QUOTEDOWN_VAR_DISABLED_NODE_TYPE, array()))
         || ( module_exists('comment') && COMMENT_NODE_OPEN != $build['#node']->comment )
    ) {
      return;
    }

**Comment by pounard** [comment]
This is supposed to be fixed now.
